//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autonoa.Solucion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Motor { get; set; }
        public string Color { get; set; }
        public string UrlImagen { get; set; }
        public string Descripcion { get; set; }
    }
}
